import { Product } from "@/features/products/lib/types";

// TODO: Replace with real data once the public product API is wired up

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "heritage-bifold",
    name: "The Heritage Bifold",
    price: 24500,
    category: "Wallets",
    color: "Black",
    createdAt: "2026-06-20T10:00:00Z",
  },
  {
    id: "2",
    slug: "minimalist-cardholder",
    name: "The Minimalist Cardholder",
    price: 12500,
    category: "Wallets",
    color: "Brown",
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "3",
    slug: "executive-folio",
    name: "The Executive Folio",
    price: 45000,
    category: "Bags",
    color: "Grey",
    createdAt: "2026-07-18T10:00:00Z",
  },
  {
    id: "4",
    slug: "anchor-key-loop",
    name: "The Anchor Key Loop",
    price: 6500,
    category: "Accessories",
    color: "Black",
    createdAt: "2026-05-28T10:00:00Z",
  },
  {
    id: "5",
    slug: "voyager-passport-cover",
    name: "The Voyager Passport Cover",
    price: 18000,
    category: "Accessories",
    color: "Tan",
    createdAt: "2026-07-22T10:00:00Z",
  },
  {
    id: "6",
    slug: "spectacle-sleeve",
    name: "The Spectacle Sleeve",
    price: 11000,
    category: "Accessories",
    color: "Grey",
    createdAt: "2026-06-02T10:00:00Z",
  },
  {
    id: "7",
    slug: "atelier-tote",
    name: "The Atelier Tote",
    price: 68000,
    category: "Bags",
    color: "Tan",
    createdAt: "2026-07-27T10:00:00Z",
  },
  {
    id: "8",
    slug: "field-messenger",
    name: "The Field Messenger",
    price: 72000,
    category: "Bags",
    color: "Brown",
    createdAt: "2026-04-15T10:00:00Z",
  },
  {
    id: "9",
    slug: "sovereign-cardholder",
    name: "The Sovereign Cardholder",
    price: 14500,
    category: "Wallets",
    color: "Tan",
    createdAt: "2026-06-30T10:00:00Z",
  },
  {
    id: "10",
    slug: "driftwood-belt",
    name: "The Driftwood Belt",
    price: 9500,
    category: "Accessories",
    color: "Brown",
    createdAt: "2026-07-10T10:00:00Z",
  },
];
